spring:
  main:
    banner-mode: "off" # Set off banner
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configuration/{application}
# only for local using
server:
  port: 8888
